//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.02 at 02:40:18 PM CET 
//


package org.visico.neighborhoodpss.plugin.buildingvisualization;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.visico.neighborhoodpss.plugin.buildingvisualization package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Buildings_QNAME = new QName("http://www.visico.org/neighborhoodpss/plugin/BuildingVisualization", "Buildings");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.visico.neighborhoodpss.plugin.buildingvisualization
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BuildingVisualizationList }
     * 
     */
    public BuildingVisualizationList createBuildingVisualizationList() {
        return new BuildingVisualizationList();
    }

    /**
     * Create an instance of {@link BuildingVisualization }
     * 
     */
    public BuildingVisualization createBuildingVisualization() {
        return new BuildingVisualization();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BuildingVisualizationList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.visico.org/neighborhoodpss/plugin/BuildingVisualization", name = "Buildings")
    public JAXBElement<BuildingVisualizationList> createBuildings(BuildingVisualizationList value) {
        return new JAXBElement<BuildingVisualizationList>(_Buildings_QNAME, BuildingVisualizationList.class, null, value);
    }

}
